name: Build

on:
  workflow_dispatch:
    inputs:
      platform:
        description: "选择打包平台"
        required: true
        default: "windows-latest"
        type: choice
        options:
          - "windows-latest"
          - "macos-latest"
      arch:
        description: '选择打包架构'
        required: true
        default: 'Windows x64'
        type: choice
        options:
          - 'Windows x64'
          - 'Windows x86'
          - 'Windows arm64'
          - 'macOS'

jobs:
  build:
    runs-on: ${{ inputs.platform }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install dependencies (webpack)
        run: npm install

      - name: Build webpack
        run: npm run build

      - name: Goto dist
        run: cd dist

      - name: Install dependencies (electron)
        run: npm install

      - name: Build Electron app
        run: |
          if [ ${{ inputs.arch }} == 'Windows x64' ]; then
            npx electron-build -w --x64
          else
            if [ ${{ inputs.arch }} == 'Windows x86' ]; then
              npx electron-build -w --ia32
            else
              if [ ${{ inputs.arch }} == 'Windows arm64' ]; then
                npx electron-build -w --arm64
              else
                if [ ${{ inputs.arch }} == 'macOS' ]; then
                  npx electron-build -m --universal
                fi
              fi
            fi
          fi

      - name: Upload dist
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.arch }}
          path: dist
