name: Build Desktop App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: 'Windows-x64'
            platform:  'windows/amd64'
            os: 'windows-latest'

          - name: 'Windows-ia32'
            platform:  'windows/386'
            os: 'windows-latest'

          - name: 'Windows-arm64'
            platform:  'windows/arm64'
            os: 'windows-latest'

          - name: 'macOS-universal'
            platform:  'darwin/universal'
            os: 'macos-latest'

          - name: 'macOS-x64'
            platform:  'darwin/amd64'
            os: 'macos-latest'

          - name: 'macOS-arm64'
            platform:  'darwin/arm64'
            os: 'macos-latest'

    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
        with:
          fetch-depth: 0

      - name: Setup Go environment
        uses: actions/setup-go@v5.0.2
        with: 
          check-latest: true
          go-version-file: 'go.mod'

      - name: Setup Node
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20

      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Build app (Windows)
        if: runner.os == 'Windows'
        run: wails build -nsis
      
      - name: Build app (macOS)
        if: runner.os == 'macOS'
        run: wails build
      
      - name: Upload artifact
        if: success() && github.event_name != 'pull_request' && github.repository == 'Super12138/Hash-Checker'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ matrix.build.name }}
          path: build/bin