name: Build macOS Release (Test)
on:
  workflow_dispatch:
jobs:
  pack:
    runs-on: macos-13
    steps:
    - uses: actions/checkout@v4
    - name: Install and Build
      run: |
        npm install
        npm run buildm
    - name: Upload file
      uses: actions/upload-artifact@v4
      with:
        name: HashChecker  # 上传后的名字
        path: dist