name: Build Desktop App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        platform:
          - name: Windows-x64
            platform: windows/amd64
            os: windows-latest
          
          - name: Windows-x32
            platform: windows/386
            os: windows-latest

          - name: Windows-arm64
            platform: windows/arm64
            os: windows-latest

          - name: macOS-universal
            platform: darwin/universal
            os: macos-latest

          - name: macOS-x64
            platform: darwin/amd64
            os: macos-latest

          - name: macOS-arm64
            platform: darwin/arm64
            os: macos-latest

    runs-on: ${{ matrix.platform.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
        with:
          fetch-depth: 0

      - name: Setup Node
        uses: actions/setup-node@v4.1.0
        with:
          node-version: 20

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # 这些目标仅在 macOS 上使用，因此将其放在 `if` 语句中，以稍微加快 Windows 和 Linux 的构建速度
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install dependencies
        run: npm install

      - name: Build app
        uses: tauri-apps/tauri-action@v0.5.16

      - name: Upload artifact
        if: success() && github.event_name != 'pull_request' && github.repository == 'Super12138/Hash-Checker'
        uses: actions/upload-artifact@v4.4.3
        with:
          name: ${{ matrix.platform.name }}
          path: |
            src-tauri/target/**/release/bundle/**/*
            src-tauri/target/**/release/Hash Checker.exe
            src-tauri/target/**/release/Hash Checker