name: Build

on:
  workflow_dispatch:
    branches: 
      - main
  
  push:
    branches: 
      - main

jobs:
  build_webpack:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build webpack
        run: npm run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: Webpack-dist
          path: ${{ github.workspace }}/dist

  build_app:
    needs: build_webpack

    strategy:
      matrix:
        os: [windows-latest, macos-13]
    runs-on: ${{ matrix.os }}
    
    steps:
      - uses: actions/setup-node@v4.0.2
        with:
          node-version: 20

      - name: Get webpack artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: Webpack-dist

      - name: Install dependencies
        run: npm install

      - name: Build app
        run: npx electron-builder --publish=never

      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4.3.3
        with:
          name: HashChecker-${{ matrix.os }}
          path: ${{ github.workspace }}/dist/*Setup*.exe

      - name: Upload macOS artifact (universal)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: HashChecker-${{ matrix.os }}-Universal
          path: ${{ github.workspace }}/dist/*-universal.dmg
          if-no-files-found: ignore
        
      - name: Upload macOS artifact (arm64)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: HashChecker-${{ matrix.os }}-arm64
          path: ${{ github.workspace }}/dist/*-arm64.dmg
          if-no-files-found: ignore

      - name: Upload macOS artifact (x64)
        uses: actions/upload-artifact@v4.3.3
        with:
          name: HashChecker-${{ matrix.os }}-x64
          path: |
            !${{ github.workspace }}/dist/*-arm64.dmg
            !${{ github.workspace }}/dist/*-universal.dmg
          if-no-files-found: ignore