name: Build

on:
  # workflow_dispatch为在Github仓库的Actions面板中手动执行
  workflow_dispatch:
  
jobs:
  buildwin:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install and Build
      run:
        cd src && npm install && npm run build
    # 步骤二的名称：将编译后的结果上传
    - name: Upload File
      # 使用预制action：上传文件，可以将执行路径打包成zip上传
      uses: actions/upload-artifact@v2
      with:
        # 上传后文件的名称
        name: windows
        # 打包的路径以及文件过滤，此为仅打包dist目录下的exe文件
        path: dist/*exe
        
  buildmac:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
    - name: Install and Build
      run:
        cd src && npm install && npm run buildm
    # 步骤二的名称：将编译后的结果上传
    - name: Upload File
      # 使用预制action：上传文件，可以将执行路径打包成zip上传
      uses: actions/upload-artifact@v2
      with:
        # 上传后文件的名称
        name: mac
        # 打包的路径以及文件过滤，此为仅打包dist目录下的dmg文件
        path: dist/*dmg
