name: Deploy
on:
  workflow_dispatch: {}
jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install
      - name: Build
        run: npm run build
      - name: Fix service-worker.js path error
        run: sed -i 's?"./workbox-2b403519"?"/Hash-Checker/workbox-2b403519"?g' dist/service-worker.js
      - uses: actions/configure-pages@v4
      - uses: actions/upload-pages-artifact@v1
        with:
          path: dist
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v1
